export const SEARCH_DIRECTORY_RECORD_TYPE = {
    USER: 'User',
    DEPARTMENT: 'Department',
    ANNOUNCEMENT: 'Announcement',
    VOICEMAIL: 'Voicemail',
    SHARED_LINES_GROUP: 'SharedLinesGroup',
    PAGING_ONLY: 'PagingOnly',
    PARK_LOCATION: 'ParkLocation',
    IVR_MENU: 'IvrMenu',
    LIMITED: 'Limited',
    APPLICATION_EXTENSION: 'ApplicationExtension',
    SITE: 'Site',
    BOT: 'Bot',
    ROOM: 'Room',
    PROXY_ADMIN: 'ProxyAdmin',
    DELEGATED_LINES_GROUP: 'DelegatedLinesGroup',
    GROUP_CALL_PICKUP: 'GroupCallPickup',
    EXTERNAL: 'External',
    ROOM_CONNECTOR: 'RoomConnector',
    UNKNOWN: 'Unknown',
};
