import type { BriefingScenario, BriefingSnapshot, BriefingWidget, Dataset, Field, Renderer, Row, Workspace } from '../src/lib/model.ts'
import { createArtifact } from '../src/lib/analytics.ts'
import { catalogSourceUrl } from '../src/lib/curatedQuestions.ts'

type Definition = Omit<BriefingWidget, 'artifactId'> & { chartType: string; x: string; y: string; series?: string; aggregation: 'sum' | 'mean'; fields: Field[]; rows: Row[]; title: string; renderer: Renderer; orientation?: 'horizontal' | 'vertical'; target?: number; labelField?: string }
const sections: BriefingWidget['section'][] = ['Needs attention', 'Team & capacity', 'AI & customer outcomes', 'Chart examples']
const queues = ['Sales', 'Billing', 'Account Services', 'Returns', 'Technical Support']
const agents = ['Avery', 'Jordan', 'Mika', 'Riley', 'Sam']
const scenarios: Record<BriefingScenario, { window: string; comparison: string; seed: number }> = {
  morning: { window: 'Previous completed operating day', comparison: 'Compared with the equivalent period across the preceding five operating days', seed: 41 },
  midday: { window: 'Today through noon', comparison: 'Compared with the same through-noon period across the preceding five operating days', seed: 73 },
}
const metric = (id: string, name: string, unit = '%'): Field => ({ id, name, type: 'number', unit, min: 0, max: 100, precision: 1 })
const category = (id: string, name: string, values: string[]): Field => ({ id, name, type: 'category', values })
const rankedRows = (categories: string[], value: string, values: number[]) => categories.map((name, index) => ({ category: name, position: index + 1, [value]: values[index] }))
const base = (id: string, section: BriefingWidget['section'], title: string, finding: string, value: string, comparison: string, severity: BriefingWidget['severity'], explanation: string, definition: string, source: BriefingWidget['source'], investigatePrompt: string, values: number[], categories: string[], renderer: Renderer, chartType = 'bar', options: Pick<Definition, 'orientation' | 'target' | 'priority' | 'labelField' | 'entity'> = {}): Definition => ({
  id, section, title, metricTitle: title, entity: categories[0], finding, value, comparison, severity, explanation, definition, source, sourceUrl: source === 'Catalog' ? catalogSourceUrl : undefined, investigatePrompt, chartType,
  x: chartType === 'scatter' ? 'position' : 'category', y: id, aggregation: 'mean', fields: [category('category', categories === agents ? 'Agent' : 'Queue', categories), metric('position', 'Rank', ''), metric(id, title.replace(/ rates?| health| quality| pressure| distribution| occupancy/gi, '').trim())], rows: rankedRows(categories, id, values), renderer, ...options,
})

function definition(scenario: BriefingScenario, index: number): Definition {
  const offset = scenario === 'morning' ? 0 : 4
  switch (index) {
    case 0: return base('abandonmentRate', 'Needs attention', 'Queue abandonment rate', `Sales abandonment is ${67 + offset}%`, `${67 + offset}%`, `+${9 + offset} pts versus baseline`, 'critical', 'Customers are leaving before an agent answers. Sales is the outlier in a five-queue comparison.', 'Abandoned interactions ÷ offered interactions. Demo target: under 45%.', 'Catalog', 'Investigate why Sales queue abandonment is rising and suggest staffing actions.', [67 + offset, 58 + offset, 54 + offset, 47 + offset, 39 + offset], queues, 'echarts', 'bar', { orientation: 'horizontal', target: 45, priority: true, entity: 'Sales' })
    case 1: return base('serviceLevel', 'Needs attention', 'Service level', `Billing is ${72 - offset}% within target`, `${72 - offset}%`, `−${8 + offset} pts versus baseline`, 'critical', 'Billing missed the 80% service objective while volume stayed above its normal range.', 'Interactions answered within the service threshold ÷ offered interactions. Demo target: 80%.', 'Catalog', 'Investigate why Billing service level is below target and identify the drivers.', [79 - offset, 72 - offset, 83 - offset, 86 - offset, 89 - offset], queues, 'echarts', 'bar', { orientation: 'horizontal', target: 80, entity: 'Billing' })
    case 2: return base('acceptanceRate', 'Needs attention', 'Agent acceptance rate', `Jordan accepted ${76 - offset}%`, `${76 - offset}%`, `−${7 + offset} pts versus baseline`, 'warning', 'Jordan’s acceptance rate has declined for two comparable windows and needs a schedule or state review.', 'Accepted offers ÷ offered interactions. Demo target: 85%.', 'Catalog', 'Investigate declining agent acceptance and compare availability by agent.', [88 - offset, 76 - offset, 84 - offset, 91 - offset, 86 - offset], agents, 'plotly', 'scatter', { target: 85, labelField: 'category', entity: 'Jordan' })
    case 3: return base('rnaRate', 'Needs attention', 'Ring-no-answer rate', `Ring-no-answer reached ${19 + offset}%`, `${19 + offset}%`, `+${6 + offset} pts versus baseline`, 'warning', 'Ring-no-answer is elevated across two queues, suggesting missed alerts or availability-state issues.', 'Ringing interactions not answered ÷ agent offers. Demo target: under 12%.', 'Catalog', 'Investigate ring-no-answer increases by queue and agent.', [12 + offset, 19 + offset, 16 + offset, 10 + offset, 14 + offset], queues, 'echarts', 'bar', { orientation: 'horizontal', target: 12, entity: 'Billing' })
    case 4: {
      const pressure = [82 + offset, 68 + offset, 54 + offset, 39 + offset, 31 + offset], occupancy = [91 - offset, 84 - offset, 78 - offset, 73 - offset, 70 - offset]
      return { ...base('occupancy', 'Team & capacity', 'Queue pressure and occupancy', `Sales occupancy is ${91 - offset}%`, `${91 - offset}%`, `+${8 - offset} pts versus baseline`, 'warning', 'High occupancy paired with rising wait pressure leaves little buffer for breaks or spikes.', 'Active handling time ÷ staffed time. Demo target: 75–85%.', 'Catalog', 'Compare queue pressure with agent occupancy and recommend capacity actions.', occupancy, queues, 'plotly', 'scatter', { priority: true, labelField: 'category', entity: 'Sales' }), x: 'waitPressure', y: 'occupancy', fields: [category('category', 'Queue', queues), metric('waitPressure', 'Wait pressure'), metric('occupancy', 'Occupancy')], rows: queues.map((name, i) => ({ category: name, waitPressure: pressure[i], occupancy: occupancy[i] })) }
    }
    case 5: {
      const afterCall = [31 + offset, 24 + offset, 20 + offset, 18 + offset, 22 + offset]
      const states: Array<[string, number[]]> = [['Available', [35 - offset, 39 - offset, 44 - offset, 48 - offset, 41 - offset]], ['In call', [22, 25, 24, 23, 25]], ['After-call work', afterCall], ['Break', [12, 12, 12, 11, 12]]]
      return { ...base('minutes', 'Team & capacity', 'Agent time distribution', `Avery spent ${31 + offset}% in after-call work`, `${31 + offset}%`, `+${5 + offset} pts versus baseline`, 'watch', 'After-call work is taking a larger share of staffed time than usual for two agents.', 'Minutes in a state ÷ total staffed minutes. Demo target: review after-call work above 25%.', 'Catalog', 'Break down agent time by state and identify coaching opportunities.', afterCall, agents, 'chartjs', 'stacked-bar', { entity: 'Avery' }), x: 'category', y: 'share', series: 'state', orientation: 'horizontal', fields: [category('category', 'Agent', agents), category('state', 'State', states.map(([name]) => name)), metric('share', 'Time share')], rows: agents.flatMap((agent, agentIndex) => states.map(([state, values]) => ({ category: agent, state, share: values[agentIndex] }))) }
    }
    case 6: return base('successRate', 'Team & capacity', 'Outbound campaign success', `Renewals reached ${43 - offset}%`, `${43 - offset}%`, `−${6 + offset} pts versus baseline`, 'watch', 'Renewals is below its campaign target while the other campaigns remain inside normal variation.', 'Successful outbound outcomes ÷ completed outbound attempts. Demo target: 48%.', 'Catalog', 'Investigate outbound campaign success rates and compare contact strategies.', [43 - offset, 51 - offset, 56 - offset, 49 - offset, 54 - offset], ['Renewals', 'Win-back', 'Trial', 'Upgrade', 'Survey'], 'echarts', 'bar', { orientation: 'horizontal', target: 48, entity: 'Renewals' })
    case 7: return base('repeatRate', 'AI & customer outcomes', 'Repeat-contact pressure', `Returns repeat contacts are ${28 + offset}%`, `${28 + offset}%`, `+${7 + offset} pts versus baseline`, 'warning', 'Returns customers are returning soon after resolution more often than in comparable periods.', 'Customers with another interaction in seven days ÷ resolved customers. Demo target: under 20%.', 'Catalog', 'Investigate repeat-contact pressure by queue and resolution outcome.', [18 + offset, 21 + offset, 24 + offset, 28 + offset, 17 + offset], queues, 'plotly', 'scatter', { target: 20, labelField: 'category', entity: 'Returns' })
    case 8: return base('qualityScore', 'AI & customer outcomes', 'AI resolution quality', `AI quality is ${82 - offset}/100`, `${82 - offset}/100`, `−${4 + offset} points versus baseline`, 'watch', 'Synthetic extension: AI answers remain useful but quality fell on handoff-heavy topics.', 'Composite resolution-quality score from completion, sentiment, and policy checks. Demo target: 85/100.', 'Synthetic extension', 'Investigate AI resolution quality and identify the topics needing improvement.', [88 - offset, 85 - offset, 82 - offset, 79 - offset, 84 - offset], ['Answers', 'Policy', 'Handoff', 'Coverage', 'Clarity'], 'echarts', 'bar', { orientation: 'horizontal', target: 85, entity: 'Handoff' })
    case 9: return base('handoffHealth', 'AI & customer outcomes', 'AI-to-human handoff health', `Handoffs complete in ${74 - offset}%`, `${74 - offset}%`, `−${9 + offset} pts versus baseline`, 'critical', 'Synthetic extension: customers are waiting longer after AI escalation and some context is incomplete.', 'Completed human handoffs with conversation context ÷ AI escalation attempts. Demo target: 85%.', 'Synthetic extension', 'Investigate AI-to-human handoff health and find where handoffs are failing.', [82 - offset, 79 - offset, 74 - offset, 86 - offset, 88 - offset], ['Intent capture', 'Routing', 'Context transfer', 'Agent accept', 'Resolution'], 'echarts', 'bar', { orientation: 'horizontal', target: 85, entity: 'Context transfer' })
    case 10: return base('interactionVolume', 'Chart examples', 'Interaction volume trend', `Volume peaked at ${124 + offset} interactions`, `${124 + offset}`, '+12% versus the prior day', 'healthy', 'A seven-day area chart is suited to showing a continuous volume trend and its daily shape.', 'Daily interactions across the synthetic support operation.', 'Synthetic extension', 'Compare the daily volume trend by channel.', [92, 101, 116, 124 + offset, 113, 98, 106], ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 'echarts', 'area', { entity: 'Thursday' })
    case 11: return { ...base('satisfactionScore', 'Chart examples', 'Handling-time relationship', 'Satisfaction falls as handling time increases in this scenario.', '−0.72', 'Correlation coefficient', 'watch', 'The regression line summarizes the relationship between handling time and customer satisfaction across the synthetic queue sample.', 'Synthetic observations are used to illustrate a linear trend, not causation.', 'Synthetic extension', 'Inspect the records behind this relationship.', [94, 89, 84, 77, 70], queues, 'plotly', 'regression', { entity: 'Queue sample' }), x: 'handlingMinutes', y: 'satisfactionScore', fields: [category('category', 'Queue', queues), metric('handlingMinutes', 'Handling time', 'minutes'), metric('satisfactionScore', 'Customer satisfaction', 'score')], rows: queues.map((name, i) => ({ category: name, handlingMinutes: [6, 9, 13, 18, 23][i], satisfactionScore: [94, 89, 84, 77, 70][i] })) }
    case 12: return base('interactionShare', 'Chart examples', 'Channel mix', 'Digital channels represent the largest share of interactions.', '42%', 'of total interactions', 'healthy', 'A pie chart shows the composition of a small set of mutually exclusive interaction channels.', 'Share of total synthetic interactions by channel.', 'Synthetic extension', 'Compare the channel mix over time.', [42, 28, 18, 12], ['Digital', 'Voice', 'Chat', 'Email'], 'plotly', 'pie', { entity: 'Digital' })
    default: return { ...base('activity', 'Chart examples', 'Queue activity pattern', 'Queue activity peaks around midday for Sales and Billing.', '84', 'highest activity index', 'healthy', 'A heatmap compares intensity across hours and queues, making concentrated activity easy to find.', 'Synthetic activity index by queue and hour.', 'Synthetic extension', 'Compare this activity pattern with queue abandonment.', [0], queues, 'echarts', 'heatmap', { entity: 'Midday' }), x: 'hour', y: 'activity', series: 'queue', fields: [category('hour', 'Hour', ['09:00', '11:00', '13:00', '15:00', '17:00']), category('queue', 'Queue', queues), metric('activity', 'Activity index', 'index')], rows: ['09:00', '11:00', '13:00', '15:00', '17:00'].flatMap((hour, hourIndex) => queues.map((queue, queueIndex) => ({ hour, queue, activity: 38 + hourIndex * 9 + queueIndex * 5 + offset }))) }
  }
}

export function ensureBriefings(workspace: Workspace): BriefingSnapshot[] {
  const snapshots = (Object.keys(scenarios) as BriefingScenario[]).map(scenario => {
    const config = scenarios[scenario]
    const widgets = sections.flatMap(section => Array.from({ length: section === 'Needs attention' ? 4 : section === 'Chart examples' ? 4 : 3 }, (_, slot) => ({ section, slot }))).map(({ section, slot }) => {
      const globalIndex = section === 'Needs attention' ? slot : section === 'Team & capacity' ? 4 + slot : section === 'AI & customer outcomes' ? 7 + slot : 10 + slot
      const source = definition(scenario, globalIndex)
      const dataset: Dataset = { id: `briefing-${scenario}-dataset-${globalIndex}`, title: source.title, seed: config.seed + globalIndex, fields: source.fields, rows: source.rows, colors: Object.fromEntries(source.rows.map((row, i) => [`category:${row.category}`, i])), createdAt: '2026-09-12T00:00:00.000Z' }
      const artifact = createArtifact(dataset, { chartType: source.chartType, x: source.x, y: source.y, series: source.series, aggregation: source.aggregation, filters: [], orientation: source.orientation, target: source.target, labelField: source.labelField }, source.title, source.renderer)
      artifact.id = `briefing-${scenario}-artifact-${globalIndex}`; artifact.notice = `${config.window}. ${config.comparison}.`
      if (!workspace.datasets.some(item => item.id === dataset.id)) workspace.datasets.push(dataset)
      if (!workspace.artifacts.some(item => item.id === artifact.id)) workspace.artifacts.push(artifact)
      return { ...source, artifactId: artifact.id } as BriefingWidget
    })
    return { id: `briefing-${scenario}`, scenario, title: scenario === 'morning' ? 'Morning supervisor briefing' : 'Midday supervisor briefing', reportingWindow: config.window, comparisonWindow: config.comparison, summary: widgets.filter(widget => widget.severity === 'critical').slice(0, 3).map(widget => `${widget.finding} (${widget.comparison})`), createdAt: '2026-09-12T00:00:00.000Z', widgets }
  })
  for (const candidate of snapshots) {
    const existing = workspace.briefings.find(item => item.id === candidate.id)
    if (!existing) { workspace.briefings.push(candidate); continue }
    for (const widget of existing.widgets) {
      const metadata = candidate.widgets.find(item => item.id === widget.id)
      if (!metadata) continue
      widget.metricTitle ??= metadata.metricTitle
      widget.entity ??= metadata.entity
      widget.priority ??= metadata.priority
      widget.sourceUrl ??= metadata.sourceUrl
      }
    for (const widget of candidate.widgets) if (!existing.widgets.some(item => item.id === widget.id)) existing.widgets.push(widget)
  }
  return workspace.briefings
}
